server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: CONFIG-SERVER-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TNemoo/config-server-service
          username:
          password:
          default-label: master
          searchPaths: "{application}"
