server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
        - id: contacts-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/contacts/**
            - Method=GET,POST
          filters:
            - AuthenticationFilter

        - id: phone-code-service
          uri: lb://PHONE-CODE-SERVICE
          predicates:
            - Path=/codes/**
            - Method=GET,POST
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: GETAWAY


