server:
  port: 8001

logging:
  level:
    by.javaguru.client.CourseServiceFeignClient: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
#  main:
#    web-application-type: reactive
  application:
    name: CONTACT-SERVICE

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuit-breaker-events,retry
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuit-breakers:
      enabled: true

resilience4j:
  circuit-breaker:
    instances:
      phone-code-service:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3

    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      phone-code-service:
        maxAttempts: 5
        waitDuration: 5000